version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: laravelsu-nginx
    working_dir: /home/forge/laravel.su
    volumes:
      - .:/home/forge/laravel.su
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx:/var/log/nginx/
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel_su

  php:
    build: docker/php
    container_name: laravelsu-php
    working_dir: /home/forge/laravel.su
    volumes:
      - .:/home/forge/laravel.su
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_su

  mysql:
    image: mariadb:10.1
    container_name: laravelsu-mysql
    working_dir: /home/forge/laravel.su
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravelsu
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
    ports:
      - "8081:3306"
    networks:
      - laravel_su

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravelsu-mailhog
    ports:
      - "8082:8025"
    networks:
      - laravel_su

  redis:
    image: redis:alpine
    container_name: laravelsu-redis
    networks:
      - laravel_su

networks:
  laravel_su:
    name: laravel_su
    driver: bridge

