version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: laravelsu-nginx
    working_dir: /home/forge/laravel.su
    volumes:
      - .:/home/forge/laravel.su
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx:/var/log/nginx/
    ports:
      - "${LARAVEL_SU_HTTP_PUBLIC_PORT:-80}:80"
    depends_on:
      - php
    networks:
      - laravel_su

  php:
    build: docker/php
    container_name: laravelsu-php
    working_dir: /home/forge/laravel.su
    volumes:
      - .:/home/forge/laravel.su
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres
    networks:
      - laravel_su

  postgres:
    image: postgres:15.1
    container_name: laravelsu-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/data/postgres:/home/db
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravelsu}
      - POSTGRES_USER=${DB_USERNAME:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "${LARAVEL_SU_DATABASE_PUBLIC_PORT:-5432}:5432"
    networks:
      - laravel_su

  node:
    build: docker/node
    container_name: laravelsu-node
    working_dir: /home/forge/laravel.su
    volumes:
      - .:/home/forge/laravel.su

networks:
  laravel_su:
    name: laravel_su
    driver: bridge

volumes:
  postgres:
